export enum ApprovalDecision {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  ESCALATE = 'ESCALATE',
  DELEGATE = 'DELEGATE',
  REQUEST_CHANGES = 'REQUEST_CHANGES',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REQUESTED_CHANGES = 'REQUESTED_CHANGES',
  SKIPPED = 'SKIPPED',
}
