export enum ApprovalStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  DELEGATED = 'DELEGATED',
  CANCELLED = 'CANCELLED',
  AWAITING_DOCUMENTATION = 'AWAITING_DOCUMENTATION',
}
