export enum ComplianceStatus {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  EXEMPT = 'EXEMPT',
  VALID = 'VALID',
  INVALID = 'INVALID',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  FLAGGED = 'FLAGGED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  COMPLIANT = 'COMPLIANT',
  NON_COMPLIANT = 'NON_COMPLIANT',
}
