export enum Department {
  FINANCE = 'FINANCE',
  PROCUREMENT = 'PROCUREMENT',
  OPERATIONS = 'OPERATIONS',
  IT = 'IT',
  LEGAL = 'LEGAL',
  AUDIT = 'AUDIT',
  SALES = 'SALES',
  HR = 'HR',
  ADMINISTRATION = 'ADMINISTRATION',
}
