export enum EntityType {
  USER = 'USER',
  ORGANIZATION = 'ORGANIZATION',
  SUPPLIER = 'SUPPLIER',
  INVOICE = 'INVOICE',
  PAYMENT = 'PAYMENT',
  APPROVAL = 'APPROVAL',
  COMPLIANCE_CHECK = 'COMPLIANCE_CHECK',
  RISK_SCORE = 'RISK_SCORE',
  AUDIT_LOG = 'AUDIT_LOG',
  FILE_ATTACHMENT = 'FILE_ATTACHMENT',
  INTEGRATION = 'INTEGRATION',
}
