export enum MatchingStatus {
  EXACT = "EXACT",
  FUZZY = "FUZZY",
  MANUAL = "MANUAL",
  UNMATCHED = "UNMATCHED",
  MATCHED = "MATCHED",
  PARTIAL_MATCH = "PARTIAL_MATCH",
  DISPUTED = "DISPUTED",
  WRITTEN_OFF = "WRITTEN_OFF",
}
