export enum PaymentMethod {
  BANK_TRANSFER = "BANK_TRANSFER",
  CHEQUE = "CHEQUE",
  CASH = "CASH",
  CREDIT_CARD = "CREDIT_CARD",
  DIRECT_DEBIT = "DIRECT_DEBIT",
  CHECK = "CHECK",
  DEBIT_CARD = "DEBIT_CARD",
  DIGITAL_WALLET = "DIGITAL_WALLET",
  EFT = "EFT",
  WIRE_TRANSFER = "WIRE_TRANSFER",
  CREDIT_NOTE = "CREDIT_NOTE",
}
