export enum ReconciliationStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  DISCREPANCY = "DISCREPANCY",
  RECONCILED = "RECONCILED",
  REVIEWED = "REVIEWED",
  DISPUTED = "DISPUTED",
  UNRECONCILED = "UNRECONCILED",
}
