export enum ScheduledTaskStatus {
  SCHEDULED = "SCHEDULED",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  SUCCESS = "SUCCESS",
  SKIPPED = "SKIPPED",
  RETRYING = "RETRYING",
}
