export enum SyncStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SUCCESS = 'SUCCESS',
  PARTIAL = 'PARTIAL',
  CANCELLED = 'CANCELLED',
}
