export enum TaxType {
  VAT = 'VAT',
  GST = 'GST',
  SALES_TAX = 'SALES_TAX',
  WITHHOLDING_TAX = 'WITHHOLDING_TAX',
  NONE = 'NONE',
  INCOME_TAX = 'INCOME_TAX',
  CUSTOMS_DUTY = 'CUSTOMS_DUTY',
  EXCISE_TAX = 'EXCISE_TAX',
}
