export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  APPROVER = 'APPROVER',
  PROCUREMENT = 'PROCUREMENT',
  VIEWER = 'VIEWER',
  AUDITOR = 'AUDITOR',
  CREDIT_CLERK = 'CREDIT_CLERK',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  FINANCIAL_MANAGER = 'FINANCIAL_MANAGER',
  EXECUTIVE = 'EXECUTIVE',
  GROUP_FINANCIAL_MANAGER = 'GROUP_FINANCIAL_MANAGER',
}
