export enum WebhookStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ERROR = "ERROR",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  PENDING = "PENDING",
  RETRYING = "RETRYING",
  TIMEOUT = "TIMEOUT",
  INVALID_SIGNATURE = "INVALID_SIGNATURE",
}
