import {
  Loader2,
  LayoutDashboard,
  FileText,
  Users,
  CheckCircle,
  BarChart3,
  Settings,
  X,
  Menu,
  Bell,
  Search,
  Plus,
  MoreHorizontal,
  ChevronDown,
  ChevronRight,
  Filter,
  Download,
  Upload,
  Trash,
  Edit,
  Eye,
  Check,
  XCircle,
  AlertCircle,
  ArrowUpDown,
  Calendar,
  Clock,
  DollarSign,
  Building,
  Mail,
  Phone,
  MapPin,
  CreditCard,
  LogOut,
  User,
  Lock,
  Shield,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  spinner: Loader2,
  logo: LayoutDashboard,
  dashboard: LayoutDashboard,
  fileText: FileText,
  users: Users,
  checkCircle: CheckCircle,
  barChart: BarChart3,
  settings: Settings,
  close: X,
  menu: Menu,
  bell: Bell,
  search: Search,
  plus: Plus,
  more: MoreHorizontal,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  filter: Filter,
  download: Download,
  upload: Upload,
  trash: Trash,
  edit: Edit,
  eye: Eye,
  check: Check,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  arrowUpDown: ArrowUpDown,
  calendar: Calendar,
  clock: Clock,
  dollarSign: DollarSign,
  building: Building,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  creditCard: CreditCard,
  logout: LogOut,
  user: User,
  lock: Lock,
  shield: Shield,
  help: HelpCircle,
};
