/**
 * CREDITORFLOW EMS - FRAUD DETECTION ENUMS
 * Version: 4.1.7
 * All enumerations for fraud detection
 */

export enum FraudDetectionMethod {
  RULE_BASED = 'RULE_BASED',
  STATISTICAL = 'STATISTICAL',
  MACHINE_LEARNING = 'MACHINE_LEARNING',
  NETWORK_ANALYSIS = 'NETWORK_ANALYSIS',
  EXTERNAL_DATA = 'EXTERNAL_DATA',
  SYSTEM = 'SYSTEM'
}

export enum RiskLevel {
  NO_RISK = 'NO_RISK',
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  LOW_MEDIUM = 'LOW_MEDIUM',
  MEDIUM = 'MEDIUM',
  MEDIUM_HIGH = 'MEDIUM_HIGH',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
  CRITICAL = 'CRITICAL',
  SEVERE = 'SEVERE',
  BLACKLISTED = 'BLACKLISTED'
}

export enum FraudSeverityLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
  SEVERE = 'SEVERE',
  BLACKLISTED = 'BLACKLISTED'
}

export enum FraudAlertPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
  IMMEDIATE = 'IMMEDIATE'
}

export enum FraudRiskCategory {
  AMOUNT_ANOMALY = 'AMOUNT_ANOMALY',
  SUPPLIER_RISK = 'SUPPLIER_RISK',
  PAYMENT_PATTERN = 'PAYMENT_PATTERN',
  TEMPORAL_ANOMALY = 'TEMPORAL_ANOMALY',
  GEOGRAPHIC_RISK = 'GEOGRAPHIC_RISK',
  BEHAVIORAL_ANOMALY = 'BEHAVIORAL_ANOMALY',
  NETWORK_RISK = 'NETWORK_RISK',
  VAT_NON_COMPLIANCE = 'VAT_NON_COMPLIANCE',
  REGULATORY_VIOLATION = 'REGULATORY_VIOLATION',
  DOCUMENT_FRAUD = 'DOCUMENT_FRAUD',
  IDENTITY_FRAUD = 'IDENTITY_FRAUD',
  SUPPLIER_IMPERSONATION = 'SUPPLIER_IMPERSONATION',
  INVOICE_DUPLICATION = 'INVOICE_DUPLICATION',
  PRICE_INFLATION = 'PRICE_INFLATION',
  GHOST_SUPPLIER = 'GHOST_SUPPLIER',
  MONEY_LAUNDERING = 'MONEY_LAUNDERING',
  BRIBERY_CORRUPTION = 'BRIBERY_CORRUPTION',
  TERRORIST_FINANCING = 'TERRORIST_FINANCING',
  SYSTEM_ERROR = 'SYSTEM_ERROR'
}

export enum FraudMitigationAction {
  ENHANCED_SCRUTINY = 'ENHANCED_SCRUTINY',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  APPROVAL_ESCALATION = 'APPROVAL_ESCALATION',
  SUPPLIER_VERIFICATION = 'SUPPLIER_VERIFICATION',
  SITE_VISIT = 'SITE_VISIT',
  REFERENCE_CHECK = 'REFERENCE_CHECK',
  BLACKLIST_CHECK = 'BLACKLIST_CHECK',
  PATTERN_ANALYSIS = 'PATTERN_ANALYSIS',
  HISTORICAL_REVIEW = 'HISTORICAL_REVIEW',
  PAYMENT_TERMS_VERIFICATION = 'PAYMENT_TERMS_VERIFICATION',
  TIMESTAMP_VALIDATION = 'TIMESTAMP_VALIDATION',
  SUBMISSION_PATTERN_ANALYSIS = 'SUBMISSION_PATTERN_ANALYSIS',
  JURISDICTION_SCREENING = 'JURISDICTION_SCREENING',
  SANCTIONS_CHECK = 'SANCTIONS_CHECK',
  PEP_SCREENING = 'PEP_SCREENING',
  BEHAVIORAL_PROFILING = 'BEHAVIORAL_PROFILING',
  ANOMALY_DETECTION = 'ANOMALY_DETECTION',
  PATTERN_RECOGNITION = 'PATTERN_RECOGNITION',
  NETWORK_ANALYSIS = 'NETWORK_ANALYSIS',
  ENTITY_RESOLUTION = 'ENTITY_RESOLUTION',
  RELATIONSHIP_MAPPING = 'RELATIONSHIP_MAPPING',
  VAT_VALIDATION = 'VAT_VALIDATION',
  TAX_NUMBER_VERIFICATION = 'TAX_NUMBER_VERIFICATION',
  SARS_COMPLIANCE_CHECK = 'SARS_COMPLIANCE_CHECK',
  REGULATORY_SCREENING = 'REGULATORY_SCREENING',
  COMPLIANCE_CHECK = 'COMPLIANCE_CHECK',
  LEGAL_REVIEW = 'LEGAL_REVIEW',
  DOCUMENT_AUTHENTICATION = 'DOCUMENT_AUTHENTICATION',
  FORENSIC_ANALYSIS = 'FORENSIC_ANALYSIS',
  SIGNATURE_VERIFICATION = 'SIGNATURE_VERIFICATION',
  IDENTITY_VERIFICATION = 'IDENTITY_VERIFICATION',
  KYC_CHECK = 'KYC_CHECK',
  BIOMETRIC_VERIFICATION = 'BIOMETRIC_VERIFICATION',
  SUPPLIER_AUTHENTICATION = 'SUPPLIER_AUTHENTICATION',
  CONTACT_VERIFICATION = 'CONTACT_VERIFICATION',
  AUTHORIZATION_CHECK = 'AUTHORIZATION_CHECK',
  DUPLICATE_DETECTION = 'DUPLICATE_DETECTION',
  FUZZY_MATCHING = 'FUZZY_MATCHING',
  HISTORICAL_SEARCH = 'HISTORICAL_SEARCH',
  PRICE_BENCHMARKING = 'PRICE_BENCHMARKING',
  MARKET_ANALYSIS = 'MARKET_ANALYSIS',
  COST_VERIFICATION = 'COST_VERIFICATION',
  PHYSICAL_ADDRESS_VERIFICATION = 'PHYSICAL_ADDRESS_VERIFICATION',
  BANK_ACCOUNT_VERIFICATION = 'BANK_ACCOUNT_VERIFICATION',
  AML_SCREENING = 'AML_SCREENING',
  TRANSACTION_MONITORING = 'TRANSACTION_MONITORING',
  SUSPICIOUS_ACTIVITY_REPORTING = 'SUSPICIOUS_ACTIVITY_REPORTING',
  ANTI_CORRUPTION_SCREENING = 'ANTI_CORRUPTION_SCREENING',
  ETHICS_CHECK = 'ETHICS_CHECK',
  COMPLIANCE_VERIFICATION = 'COMPLIANCE_VERIFICATION',
  CTF_SCREENING = 'CTF_SCREENING',
  SANCTIONS_LIST_CHECK = 'SANCTIONS_LIST_CHECK',
  IMMEDIATE_ESCALATION = 'IMMEDIATE_ESCALATION',
  PAYMENT_HOLD = 'PAYMENT_HOLD',
  SUPPLIER_SUSPENSION = 'SUPPLIER_SUSPENSION',
  REGULATORY_REPORTING = 'REGULATORY_REPORTING',
  STANDARD_REVIEW = 'STANDARD_REVIEW',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  AUTOMATED_APPROVAL = 'AUTOMATED_APPROVAL'
}

export enum FraudInvestigationStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_EVIDENCE = 'PENDING_EVIDENCE',
  PENDING_ANALYSIS = 'PENDING_ANALYSIS',
  PENDING_REVIEW = 'PENDING_REVIEW',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  COMPLETED = 'COMPLETED',
  ESCALATED = 'ESCALATED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED'
}

export enum FraudCaseStatus {
  REPORTED = 'REPORTED',
  UNDER_INVESTIGATION = 'UNDER_INVESTIGATION',
  SUSPECTED = 'SUSPECTED',
  CONFIRMED = 'CONFIRMED',
  DISMISSED = 'DISMISSED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  ESCALATED_TO_REGULATOR = 'ESCALATED_TO_REGULATOR',
  ESCALATED_TO_LAW_ENFORCEMENT = 'ESCALATED_TO_LAW_ENFORCEMENT',
  LITIGATION_PENDING = 'LITIGATION_PENDING',
  LITIGATION_IN_PROGRESS = 'LITIGATION_IN_PROGRESS',
  LITIGATION_RESOLVED = 'LITIGATION_RESOLVED',
  SETTLEMENT_NEGOTIATION = 'SETTLEMENT_NEGOTIATION',
  SETTLEMENT_COMPLETED = 'SETTLEMENT_COMPLETED'
}

export enum FraudEvidenceType {
  DOCUMENTARY = 'DOCUMENTARY',
  TESTIMONIAL = 'TESTIMONIAL',
  CIRCUMSTANTIAL = 'CIRCUMSTANTIAL',
  DIGITAL = 'DIGITAL',
  FORENSIC = 'FORENSIC',
  EXPERT_OPINION = 'EXPERT_OPINION',
  REGULATORY_FILING = 'REGULATORY_FILING',
  INSURANCE_CLAIM = 'INSURANCE_CLAIM',
  LEGAL_OPINION = 'LEGAL_OPINION',
  WITNESS_STATEMENT = 'WITNESS_STATEMENT'
}

export enum FraudEvidenceSource {
  INTERNAL_SYSTEM = 'INTERNAL_SYSTEM',
  EXTERNAL_SYSTEM = 'EXTERNAL_SYSTEM',
  THIRD_PARTY = 'THIRD_PARTY',
  REGULATORY_BODY = 'REGULATORY_BODY',
  LAW_ENFORCEMENT = 'LAW_ENFORCEMENT',
  COURT = 'COURT',
  AUDITOR = 'AUDITOR',
  INVESTIGATOR = 'INVESTIGATOR',
  WHISTLEBLOWER = 'WHISTLEBLOWER',
  PUBLIC_RECORD = 'PUBLIC_RECORD'
}

export enum FraudCaseResolution {
  NO_FRAUD_DETECTED = 'NO_FRAUD_DETECTED',
  MINOR_IRREGULARITY = 'MINOR_IRREGULARITY',
  MATERIAL_IRREGULARITY = 'MATERIAL_IRREGULARITY',
  FRAUD_CONFIRMED = 'FRAUD_CONFIRMED',
  FRAUD_SUSPECTED = 'FRAUD_SUSPECTED',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
  CASE_DISMISSED = 'CASE_DISMISSED',
  SETTLEMENT_REACHED = 'SETTLEMENT_REACHED',
  RECOVERY_COMPLETED = 'RECOVERY_COMPLETED',
  LITIGATION_LOST = 'LITIGATION_LOST',
  LITIGATION_WON = 'LITIGATION_WON',
  REGULATORY_ACTION_TAKEN = 'REGULATORY_ACTION_TAKEN',
  CRIMINAL_PROSECUTION = 'CRIMINAL_PROSECUTION',
  CIVIL_PROSECUTION = 'CIVIL_PROSECUTION'
}

export enum FraudLossEstimate {
  NO_LOSS = 'NO_LOSS',
  MINOR_LOSS = 'MINOR_LOSS',
  MODERATE_LOSS = 'MODERATE_LOSS',
  SIGNIFICANT_LOSS = 'SIGNIFICANT_LOSS',
  MAJOR_LOSS = 'MAJOR_LOSS',
  CATASTROPHIC_LOSS = 'CATASTROPHIC_LOSS'
}

export enum FraudRecoveryStatus {
  NOT_INITIATED = 'NOT_INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  PARTIAL_RECOVERY = 'PARTIAL_RECOVERY',
  FULL_RECOVERY = 'FULL_RECOVERY',
  RECOVERY_FAILED = 'RECOVERY_FAILED',
  RECOVERY_ABANDONED = 'RECOVERY_ABANDONED',
  RECOVERY_PENDING_LITIGATION = 'RECOVERY_PENDING_LITIGATION',
  RECOVERY_PENDING_SETTLEMENT = 'RECOVERY_PENDING_SETTLEMENT'
}

export enum FraudRegulatoryImpact {
  NO_IMPACT = 'NO_IMPACT',
  MINOR_IMPACT = 'MINOR_IMPACT',
  MODERATE_IMPACT = 'MODERATE_IMPACT',
  SIGNIFICANT_IMPACT = 'SIGNIFICANT_IMPACT',
  MAJOR_IMPACT = 'MAJOR_IMPACT',
  REGULATORY_ACTION = 'REGULATORY_ACTION',
  LICENSE_REVOCATION = 'LICENSE_REVOCATION',
  CRIMINAL_PROSECUTION = 'CRIMINAL_PROSECUTION',
  CIVIL_PENALTIES = 'CIVIL_PENALTIES',
  REPUTATIONAL_DAMAGE = 'REPUTATIONAL_DAMAGE'
}

export enum FraudNotificationRecipient {
  FRAUD_MANAGER = 'FRAUD_MANAGER',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  RISK_MANAGER = 'RISK_MANAGER',
  CHIEF_FINANCIAL_OFFICER = 'CHIEF_FINANCIAL_OFFICER',
  CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
  BOARD_OF_DIRECTORS = 'BOARD_OF_DIRECTORS',
  AUDIT_COMMITTEE = 'AUDIT_COMMITTEE',
  REGULATORY_BODY = 'REGULATORY_BODY',
  LAW_ENFORCEMENT = 'LAW_ENFORCEMENT',
  INSURANCE_PROVIDER = 'INSURANCE_PROVIDER'
}

export enum FraudNotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',
  PHONE_CALL = 'PHONE_CALL',
  SECURE_PORTAL = 'SECURE_PORTAL',
  IN_PERSON = 'IN_PERSON',
  COURIER = 'COURIER',
  REGULATORY_FILING = 'REGULATORY_FILING'
}

export enum FraudEscalationPath {
  FRAUD_ANALYST = 'FRAUD_ANALYST',
  FRAUD_MANAGER = 'FRAUD_MANAGER',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  RISK_MANAGER = 'RISK_MANAGER',
  CHIEF_FINANCIAL_OFFICER = 'CHIEF_FINANCIAL_OFFICER',
  CHIEF_EXECUTIVE_OFFICER = 'CHIEF_EXECUTIVE_OFFICER',
  BOARD_OF_DIRECTORS = 'BOARD_OF_DIRECTORS',
  AUDIT_COMMITTEE = 'AUDIT_COMMITTEE',
  REGULATORY_BODY = 'REGULATORY_BODY',
  LAW_ENFORCEMENT = 'LAW_ENFORCEMENT'
}

export enum FraudEscalationLevel {
  LEVEL_1 = 'LEVEL_1',
  LEVEL_2 = 'LEVEL_2',
  LEVEL_3 = 'LEVEL_3',
  LEVEL_4 = 'LEVEL_4',
  LEVEL_5 = 'LEVEL_5',
  CRITICAL = 'CRITICAL',
  IMMEDIATE = 'IMMEDIATE'
}

export enum FraudPreventiveControl {
  SEGREGATION_OF_DUTIES = 'SEGREGATION_OF_DUTIES',
  APPROVAL_WORKFLOWS = 'APPROVAL_WORKFLOWS',
  ACCESS_CONTROLS = 'ACCESS_CONTROLS',
  BACKGROUND_CHECKS = 'BACKGROUND_CHECKS',
  DUE_DILIGENCE = 'DUE_DILIGENCE'
}

export enum FraudDetectiveControl {
  DATA_ANALYTICS = 'DATA_ANALYTICS',
  AUDIT_TRAILS = 'AUDIT_TRAILS',
  RECONCILIATIONS = 'RECONCILIATIONS',
  MONITORING_ALERTS = 'MONITORING_ALERTS',
  WHISTLEBLOWER_HOTLINE = 'WHISTLEBLOWER_HOTLINE'
}

export enum FraudCorrectiveControl {
  INCIDENT_RESPONSE = 'INCIDENT_RESPONSE',
  RECOVERY_PROCEDURES = 'RECOVERY_PROCEDURES',
  DISCIPLINARY_ACTION = 'DISCIPLINARY_ACTION',
  PROCESS_IMPROVEMENTS = 'PROCESS_IMPROVEMENTS',
  TRAINING_PROGRAMS = 'TRAINING_PROGRAMS'
}

export enum FraudCompensatingControl {
  MANUAL_REVIEWS = 'MANUAL_REVIEWS',
  SUPERVISORY_CONTROLS = 'SUPERVISORY_CONTROLS',
  EXCEPTION_REPORTING = 'EXCEPTION_REPORTING'
}

export enum FraudControlEffectiveness {
  INEFFECTIVE = 'INEFFECTIVE',
  PARTIALLY_EFFECTIVE = 'PARTIALLY_EFFECTIVE',
  EFFECTIVE = 'EFFECTIVE',
  HIGHLY_EFFECTIVE = 'HIGHLY_EFFECTIVE'
}

export enum FraudControlMaturity {
  INITIAL = 'INITIAL',
  DEVELOPING = 'DEVELOPING',
  DEFINED = 'DEFINED',
  MANAGED = 'MANAGED',
  OPTIMIZED = 'OPTIMIZED'
}

export enum FraudRiskAppetite {
  CONSERVATIVE = 'CONSERVATIVE',
  MODERATE = 'MODERATE',
  AGGRESSIVE = 'AGGRESSIVE'
}

export enum FraudRiskTolerance {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH'
}
