/**
 * CREDITORFLOW EMS - FRAUD SCORER MODULE
 * Version: 4.1.7
 * Main entry point for fraud detection functionality
 */

// Core class
export { FraudScorer } from './core';
export { default } from './core';

// Types and interfaces
export type {
  FraudScoringContext,
  AmountRiskAnalysis,
  SupplierAgeRiskAnalysis,
  SupplierRiskProfileAnalysis,
  PaymentPatternRiskAnalysis,
  TemporalAnomalyRiskAnalysis,
  GeographicRiskAnalysis,
  BehavioralRiskAnalysis,
  NetworkRiskAnalysis,
  VATComplianceRiskAnalysis,
  RegulatoryRiskAnalysis,
  AggregatedRiskAnalysis,
  FraudScoringInput,
  FraudScoringResult,
  FraudRiskFactor,
  FraudConfidenceInterval,
  FraudModelVersion,
  FraudScoringMetadata,
  FraudAuditTrail,
  FraudSLATimeline,
  FraudInvestigationTimeline,
  FraudCaseTimeline,
  FraudEvidenceChain,
  FraudWitnessStatement,
  FraudExpertOpinion,
  FraudLegalOpinion,
  FraudRegulatoryFiling,
  FraudInsuranceClaim,
  FraudRecoveryAction,
  FraudRiskCapacity,
  FraudRiskExposure,
  FraudRiskResidual,
  FraudRiskInherent,
  FraudRiskMitigated,
  FraudRiskTransfer,
  FraudRiskAcceptance,
  FraudRiskAvoidance,
  FraudRiskReduction,
  FraudRiskSharing,
  FraudRiskFinancing,
  FraudRiskMonitoring,
  FraudRiskReporting,
  FraudRiskGovernance,
  FraudRiskOwnership,
  FraudRiskAccountability,
  FraudRiskCulture,
  FraudRiskAwareness,
  FraudRiskTraining,
  FraudRiskAssessment,
  FraudRiskTreatment,
  FraudRiskReview,
  FraudRiskCommunication,
  FraudRiskDocumentation,
  FraudRiskRegister,
  FraudRiskHeatmap,
  FraudRiskDashboard,
  FraudRiskKPI,
  FraudRiskMetric,
  FraudRiskIndicator,
  FraudRiskThreshold,
  FraudRiskLimit,
  FraudRiskBoundary,
  FraudRiskAppetiteStatement,
  FraudRiskPolicy,
  FraudRiskFramework,
  FraudRiskMethodology,
  FraudRiskStandard,
  FraudRiskGuideline,
  FraudRiskProcedure,
  FraudRiskControl,
  FraudRiskMitigationPlan,
  FraudRiskTreatmentPlan,
  FraudRiskResponsePlan,
  FraudRiskContingencyPlan,
  FraudRiskBusinessContinuityPlan,
  FraudRiskDisasterRecoveryPlan,
  FraudRiskIncidentResponsePlan,
  FraudRiskCrisisManagementPlan,
  FraudRiskCommunicationPlan,
  FraudRiskStakeholderEngagementPlan,
  FraudRiskTrainingPlan,
  FraudRiskAwarenessPlan,
  FraudRiskCulturePlan,
  FraudRiskGovernancePlan,
  FraudRiskMonitoringPlan,
  FraudRiskReportingPlan,
  FraudRiskReviewPlan,
  FraudRiskDocumentationPlan,
  FraudRiskRegisterPlan,
  FraudRiskHeatmapPlan,
  FraudRiskDashboardPlan,
  FraudRiskKPIPlan,
  FraudRiskMetricPlan,
  FraudRiskIndicatorPlan,
  FraudRiskThresholdPlan,
  FraudRiskLimitPlan,
  FraudRiskBoundaryPlan,
  FraudRiskAppetiteStatementPlan,
  FraudRiskPolicyPlan,
  FraudRiskFrameworkPlan,
  FraudRiskMethodologyPlan,
  FraudRiskStandardPlan,
  FraudRiskGuidelinePlan,
  FraudRiskProcedurePlan,
  FraudRiskControlPlan,
  FraudRiskMitigationPlanPlan,
  FraudRiskTreatmentPlanPlan,
  FraudRiskResponsePlanPlan,
  FraudRiskContingencyPlanPlan,
  FraudRiskBusinessContinuityPlanPlan,
  FraudRiskDisasterRecoveryPlanPlan,
  FraudRiskIncidentResponsePlanPlan,
  FraudRiskCrisisManagementPlanPlan,
  FraudRiskCommunicationPlanPlan,
  FraudRiskStakeholderEngagementPlanPlan,
  FraudRiskTrainingPlanPlan,
  FraudRiskAwarenessPlanPlan,
  FraudRiskCulturePlanPlan,
  FraudRiskGovernancePlanPlan,
  FraudRiskMonitoringPlanPlan,
  FraudRiskReportingPlanPlan,
  FraudRiskReviewPlanPlan,
  FraudRiskDocumentationPlanPlan,
  FraudRiskRegisterPlanPlan,
  FraudRiskHeatmapPlanPlan,
  FraudRiskDashboardPlanPlan,
  FraudRiskKPIPlanPlan,
  FraudRiskMetricPlanPlan,
  FraudRiskIndicatorPlanPlan,
  FraudRiskThresholdPlanPlan,
  FraudRiskLimitPlanPlan,
  FraudRiskBoundaryPlanPlan,
  FraudRiskAppetiteStatementPlanPlan,
  FraudRiskPolicyPlanPlan,
  FraudRiskFrameworkPlanPlan,
  FraudRiskMethodologyPlanPlan,
  FraudRiskStandardPlanPlan,
  FraudRiskGuidelinePlanPlan,
  FraudRiskProcedurePlanPlan,
  FraudRiskControlPlanPlan
} from './types';

// Enums (values, not types)
export {
  FraudDetectionMethod,
  RiskLevel,
  FraudSeverityLevel,
  FraudAlertPriority,
  FraudMitigationAction,
  FraudRiskCategory,
  FraudInvestigationStatus,
  FraudCaseStatus,
  FraudEvidenceType,
  FraudEvidenceSource,
  FraudCaseResolution,
  FraudLossEstimate,
  FraudRecoveryStatus,
  FraudRegulatoryImpact,
  FraudNotificationRecipient,
  FraudNotificationChannel,
  FraudEscalationPath,
  FraudEscalationLevel,
  FraudPreventiveControl,
  FraudDetectiveControl,
  FraudCorrectiveControl,
  FraudCompensatingControl,
  FraudControlEffectiveness,
  FraudControlMaturity,
  FraudRiskAppetite,
  FraudRiskTolerance
} from './types';

// Exception class
export { FraudScoringException } from './types';

// Constants
export {
  RISK_THRESHOLDS,
  RISK_WEIGHTS,
  SA_COMPLIANCE_RULES,
  MODEL_VERSION,
  CONFIDENCE_INTERVALS,
  RISK_CATEGORIES,
  SEVERITY_LEVELS,
  ALERT_PRIORITIES,
  MITIGATION_ACTIONS,
  INVESTIGATION_STATUSES,
  CASE_STATUSES,
  EVIDENCE_TYPES,
  EVIDENCE_SOURCES,
  CASE_RESOLUTIONS,
  LOSS_ESTIMATES,
  RECOVERY_STATUSES,
  REGULATORY_IMPACTS,
  NOTIFICATION_RECIPIENTS,
  NOTIFICATION_CHANNELS,
  ESCALATION_PATHS,
  ESCALATION_LEVELS,
  SLA_TIMELINES
} from './constants';

// Scoring functions
export {
  aggregateRiskScores,
  determineRiskLevel,
  determineSeverityLevel,
  generateRiskFactors,
  generateMitigationActions,
  calculateConfidenceInterval,
  determineAlertPriority,
  determineEscalationPath
} from './scoring';

// Analyzers
export { calculateAmountRisk } from './analyzers/amount-analyzer';
export { calculateSupplierAgeRisk, calculateSupplierRiskProfile } from './analyzers/supplier-analyzer';
export { calculatePaymentPatternRisk } from './analyzers/payment-analyzer';
export { calculateTemporalAnomalyRisk } from './analyzers/temporal-analyzer';
export { calculateGeographicRisk } from './analyzers/geographic-analyzer';
export { calculateBehavioralRisk } from './analyzers/behavioral-analyzer';
export { calculateNetworkRisk } from './analyzers/network-analyzer';
export { calculateVATComplianceRisk } from './analyzers/vat-analyzer';
export { calculateRegulatoryRisk } from './analyzers/regulatory-analyzer';
